filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: ~
    ignore_older: 0

queue.mem:
  events: 4096
  flush.min_events: 1
  flush.timeout: 1s

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # Если включена безопасность, раскомментируй и добавь:
  # username: elastic
  # password: changeme

setup.kibana:
  host: "http://kibana:5601"

setup.ilm.enabled: false

logging:
  level: info
  to_files: true
  files:
    path: /usr/share/filebeat/logs
    name: filebeat
    keepfiles: 7
    permissions: 0644
